### PR TITLE
need to exclude ourselves when looking up blueprints

### LINKED ISSUE #114: Blueprints don't work with Ember 2.6
Hi!
I noticed the addon's blueprints stopped working after migrating to Ember-CLI 2.6.1:
```
npm install -g ember-cli@2.6.1
ember new newapp
cd newapp
ember generate component working-component
ember install ember-cli-coffeescript
ember generate component non-working-component

```

### PR DESCRIPTION
**Pull request by kbullaughey**
This fixes #114. 

As I understand things, the coffeescript blueprints relied on finding the non-coffeescript blueprint using `lookupBlueprint`. Now that the blueprints have moved into the `ember-cli-legacy-blueprints` addon, this lookup wasn't working. I found I needed to exclude the coffeescript blueprints when the legacy blueprints were searched for. I accomplished this using a new method, `ancestralBlueprint` that I stashed in `lib/utilities/ancestral-blueprint`.

Not sure this is the optimal strategy, but it seems to work, and I was able to generate all the blueprints that rely on `lookupBlueprint`.

### CODE REVIEW

**Comment by mazondo** [comment]
Can we get this merged in, or is there a better solution coming?

**Comment by kimroen** [comment]
I'm very sorry that I've left this and other projects hanging. I'll merge this in now, then try out some things manually, and release a new version with this and some other fixes (hopefully soon, but I can't promise anything).

I'll need to figure out if this breaks on older versions of ember-cli or not, because if it does then I need to bump the major version number, and I kind of want to implement tests before I do so.

Thank you very much for looking in to this.

**Comment by dimul** [comment]
This fixes #116

**Comment by kimroen** [comment]
This has now been released as `v1.15.0`, with some tweaks (#118) to make it work on older versions of Ember CLI as well.

Thank you again for your help, and for being patient with me. 🎈

**Pull request merged**
