### PR TITLE
only install required lodash functions

### PR DESCRIPTION
**Pull request by jakesjews**
This should reduce the install size by a few megabytes.

### CODE REVIEW

**Comment by jakesjews** [comment]
Im not sure why the build failed `ember try ember-release` works locally

**Comment by mriska** [comment]
The error it gives is:
`No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.`

I have also see this in my projects from time to time. Unfortunately it is indeterministic and does not occur on every test. I am trying to track down the error but have not managed to do so yet. 

Restarting the individual Travis build that failed usually results in a non-failing build.

@kimroen Could you try to restart the failing builds and see if they turn green?

**Comment by kimroen** [comment]
I have actually restarted them once already, but running them again now! 👍

**Comment by kimroen** [comment]
Yay, thank you very much!

**Pull request merged**
