### PR TITLE
Testing Travis...

### PR DESCRIPTION
**Pull request by philipbjorge**

### CODE REVIEW

**Comment by philipbjorge** [comment]
Oops. Made this against wrong repo.

**Comment by kimroen** [comment]
Looks good though, nice job :smile: (Let me know if you come up with a testing-system for it—I'd love to copy that :wink: )

**Comment by philipbjorge** [comment]
Thanks haha.

On testing, I stole it from https://github.com/babel/ember-cli-babel
It's just a basic smoke test, but it does fail when you break everything :).

**Comment by kimroen** [comment]
True, but what I'm missing is testing the other functionality like blueprints against multiple versions of ember-cli and testing the other things like linting.

**Comment by philipbjorge** [comment]
Yeah I have no clue on testing those aspects, nor have I looked for examples yet.

As far as blueprints are concerned, I wouldn't be surprised if there isn't a testing strategy given that blueprints are inherently versioned since they're included with ember-cli...

I'll be sure to let you know if I find anything interesting.

**Comment by kimroen** [comment]
Thanks! :+1:

**Pull request closed without merging**
