### PR TITLE
Redo components to match ember-cli

### PR DESCRIPTION
**Pull request by kimroen**
Implementing the changes to components as implemented here and elsewhere: https://github.com/ember-cli/ember-cli/pull/3356

This is a fairly straight-forward change which mirrors the ember-cli one in most ways.

- For use in apps, nothing should change
- For use in addons, the component and template is now rendered to the `addon` folder, and a javascript-file is generated in `app`. This is the recommended way forward.

To make this happen, I'm overriding and changing some strings in `locals` in the base blueprint, but the superclass takes care of the logic of picking which path to take. Because we want javascript in the `app`-folder, letting the built-in `component-addon` blueprint do its thing works out here.

### CODE REVIEW

**Comment by kimroen** [comment]
This seems to be a bit in flux in ember-cli, so I'll hold off on this change for now.

**Comment by kimroen** [comment]
The great @artsyca figured this one out in #75.

Everything should now be good to finish implementing this. Tomorrow!

**Comment by artsyca** [comment]
:+1: Looking forward! Many thanks for your great work on this architecture!

**Comment by kimroen** [comment]
I ran in to an issue overriding some things, which I reported here: https://github.com/ember-cli/ember-cli/issues/4001

**Comment by kimroen** [comment]
@artsyca Released 0.11.0 with this and some other things.

**Pull request merged**
